# Generated by Django 2.0.7 on 2018-09-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auroraaggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=300)),
                ('transcount', models.IntegerField(default=0)),
                ('avgResponseTime', models.FloatField(default=0.0)),
                ('medResponseTime', models.FloatField(default=0.0)),
                ('maxResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='auroraaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=300)),
                ('transcount', models.IntegerField(default=0)),
                ('avgResponseTime', models.FloatField(default=0.0)),
                ('medResponseTime', models.FloatField(default=0.0)),
                ('maxResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='auroradmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=300)),
                ('transcount', models.IntegerField(default=0)),
                ('avgResponseTime', models.FloatField(default=0.0)),
                ('medResponseTime', models.FloatField(default=0.0)),
                ('maxResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='auroraice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=300)),
                ('transcount', models.IntegerField(default=0)),
                ('avgResponseTime', models.FloatField(default=0.0)),
                ('medResponseTime', models.FloatField(default=0.0)),
                ('maxResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='auroramlife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=300)),
                ('transcount', models.IntegerField(default=0)),
                ('avgResponseTime', models.FloatField(default=0.0)),
                ('medResponseTime', models.FloatField(default=0.0)),
                ('maxResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='auroratps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=300)),
                ('transcount', models.IntegerField(default=0)),
                ('avgResponseTime', models.FloatField(default=0.0)),
                ('medResponseTime', models.FloatField(default=0.0)),
                ('maxResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('averageResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('averageResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('averageResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('averageResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=300)),
                ('transactionCount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('transactionCount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('transactionCount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=300)),
                ('transcount', models.IntegerField(default=0)),
                ('avgResponseTime', models.FloatField(default=0.0)),
                ('medResponseTime', models.FloatField(default=0.0)),
                ('maxResponseTime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='endpointavgtime',
            old_name='time',
            new_name='averageResponseTime',
        ),
    ]
