# Generated by Django 2.0.7 on 2018-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='endpointavgtime1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
    ]
