# Generated by Django 2.0.7 on 2018-09-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20180912_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel',
            new_name='auroradistribution',
        ),
    ]
