# Generated by Django 2.0.7 on 2018-08-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='endpointavgtime6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='endpointavgtime7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
    ]
