# Generated by Django 2.0.7 on 2018-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20180916_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=300)),
            ],
        ),
    ]
