# Generated by Django 2.0.7 on 2018-09-20 15:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons_for_childcare', multiselectfield.db.fields.MultiSelectField(choices=[('working', 'Working'), ('training', 'Training'), ('teen_parent', 'Teen Parent'), ('child_disability', 'Working W/Child With A Disability'), ('adult_disability', 'Adult W/Disability')], max_length=62)),
            ],
        ),
    ]
