# Generated by Django 2.0.7 on 2018-09-20 16:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_enrollmentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='VizInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tog', multiselectfield.db.fields.MultiSelectField(max_length=200)),
                ('vis', multiselectfield.db.fields.MultiSelectField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='reasons_for_childcare',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('working', 'Working'), ('training', 'Training'), ('teen_parent', 'Teen Parent'), ('child_disability', 'Working W/Child With A Disability and'), ('adult_disability', 'Adult W/Disability')], max_length=62),
        ),
    ]
