# Generated by Django 2.0.7 on 2018-09-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20180920_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vizinfomodel',
            name='vis',
        ),
    ]
