# Generated by Django 2.0.7 on 2018-09-20 18:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_vizinfomodel_vis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='reasons_for_childcare',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
