# Generated by Django 2.0.7 on 2018-09-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20180921_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='auroraerrormethodsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorType', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=300)),
                ('s2aurora01p', models.FloatField(default=0.0)),
                ('s2aurora03p', models.FloatField(default=0.0)),
                ('s2aurora05p', models.FloatField(default=0.0)),
                ('All', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='auroraerrorsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorType', models.CharField(max_length=300)),
                ('s2aurora01p', models.FloatField(default=0.0)),
                ('s2aurora03p', models.FloatField(default=0.0)),
                ('s2aurora05p', models.FloatField(default=0.0)),
                ('All', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='auroramethodsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorType', models.CharField(max_length=300)),
                ('s2aurora01p', models.FloatField(default=0.0)),
                ('s2aurora03p', models.FloatField(default=0.0)),
                ('s2aurora05p', models.FloatField(default=0.0)),
                ('All', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='aurorasummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=300)),
                ('timeStamp', models.FloatField(default=0.0)),
            ],
        ),
    ]
